WHITESPACE = _{ " " | "\t" | "\n" | "\r" | ("#" ~ (!"\n" ~ ANY)*) }

program = { SOI ~ statement* ~ EOI }

statement = { variable_declaration | assignment | output_statement | if_statement | while_statement | for_statement | break_statement | continue_statement | function_definition | return_statement }

variable_declaration = { identifier ~ "'ı" ~ type_keyword ~ "olarak" ~ "tanımla" }

assignment = { identifier ~ "=" ~ expression }

output_statement = { "söyle" ~ expression }

expression = { term ~ (operator ~ term)* }

term = { function_call | literal | identifier }

operator = { "<=" | "<" | ">=" | ">" | "+" }

type_keyword = @{ "tamsayı" | "metin" | "ondalıklı" | "mantıksal" }

literal = { string_literal | float_literal | int_literal | boolean_literal }

string_literal = { "\"" ~ (!"\"" ~ ANY)* ~ "\"" }

int_literal = { ASCII_DIGIT+ }

float_literal = { ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT+ }

boolean_literal = @{ "doğru" | "yanlış" }

identifier = @{ (ASCII_ALPHA | "ğ" | "ü" | "ş" | "ö" | "ç" | "ı") ~ (ASCII_ALPHANUMERIC | "_" | "ğ" | "ü" | "ş" | "ö" | "ç" | "ı")* }

condition = { expression }

control_block = { statement* }

range_spec = { expression ~ "dan" ~ expression ~ ("adım" ~ expression)? }

if_statement = { "eğer" ~ condition ~ "ise" ~ control_block ~ ("yoksa" ~ control_block)? ~ "son" }

while_statement = { "döngü" ~ condition ~ "ise" ~ control_block ~ "son" }

for_statement = { "için" ~ identifier ~ "in" ~ range_spec ~ "ise" ~ control_block ~ "son" }

break_statement = { "durdur" }

continue_statement = { "devam" }

return_statement = { "return" ~ expression? }

return_part = { "->" ~ type_keyword }

function_definition = { "fonksiyon" ~ identifier ~ "(" ~ parameter_list? ~ ")" ~ return_part? ~ "{" ~ statement* ~ "}" }

parameter_list = { parameter ~ ("," ~ parameter)* }

parameter = { identifier ~ ":" ~ type_keyword }

function_call = { identifier ~ "(" ~ argument_list? ~ ")" }

argument_list = { expression ~ ("," ~ expression)* }
